spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://3.19.194.142:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
logging:
  file:
    path: /logs/smc/mssmc-eureka
  pattern:
    console: "%d %-5level %logger : %msg%n"  
    file: "%d %-5level [%thread] %logger : %msg%n"   
  level:
    '[org.springframework]': info
    '[mx.com.totalplay.smc]': debug
