export const DASHBOARD = {
    ENLACES_VISTA_GENERAL: 'ENLACES_VISTA_GENERAL',
    ENLACES_AFECTACIONES: 'ENLACES_AFECTACIONES',
    ENLACES_ALARMAS: 'ENLACES_ALARMAS',
    ENLACES_METRICAS: 'ENLACES_METRICAS',
    MAPA_ENLACES_INALCANZABLES: 'MAPA_ENLACES_INALCANZABLES',
    ENLACES_TICKETS: 'ENLACES_TICKETS'
};