package mx.com.totalplay.smc.commons.model;

public enum EmailType {
	INVITACION_USR_TP, INVITACION_CTE, INVITACION_CTE_USR, CODIGO, CODIGO_RECUPERAR_PWD, INVITACION_USR, INVITACION_USR_CTE,
	BIENVENIDA_CTE
}
